# System Configuration

# Name of the large model
llm_name: GPT-3.5-turbo
llm_key: YOUR_API_KEY

# Name of the patterns storage system
patterns_storage: elasticsearch
es_host: http://10.110.153.75:9200
pattern_index_name: patterns

# Version of the system
version: 1.0.0